name: CI/CD Pipeline for Dockerized Spring Boot App

on:
  workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. application.properties 생성
      - name: Create application.properties
        run: |
          mkdir -p src/main/resources  # 디렉토리 생성
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      # 4. Maven 빌드
      - name: Build with Maven
        run: mvn -B package --file pom.xml
